### PR TITLE
Use Termwiz, display colours, use icons

### LINKED ISSUE #1: love it! suggestion...
Nice job Reilly. It's quite fun to play with in nushell. 

One thing that I'd find interesting is if escape-artist colored the text in the web browser a similar color to what it was in the terminal. I find myself struggling to find certain things in the browser sometimes. You may be able to find a crate that does this but in nushell, in the `to html` command we use `setup_html_color_regexes()` and `run_regexes()`.

Just an idea. Thanks for the fun!

BTW - My prompt is epic. 🤣 
image

image

### LINKED ISSUE #3: Bell character not rendered correctly
Repro: run `echo -e "\07"`, it gets displayed as an "Execute" without any info

image

### LINKED ISSUE #6: Replace `vte` with `termwiz`
I've been looking into VTE parser crates and [`termwiz`](https://crates.io/crates/termwiz) looks super. It has a lot of nice functionality that `vte` doesn't, it gives a lot more semantic info about escapes instead of just the basics.

### PR DESCRIPTION
**Pull request by rgwood**
Some big changes that close #6, #3, #2:
- Now using `termwiz` instead of `vte` for parsing escape codes. This gives us a lot more semantic information about escape codes
- We now keep track of foreground+background colour and use that to colour text in the web UI
- We display icons for some common sequences and generally are more succinct in what we display

All together I think this makes it a lot easier to see what's going on in the web UI.

image

### CODE REVIEW

**Comment by fdncred** [comment]
Just installed and already have a few "why are we doing that" questions. 🚀 This change makes it much easier to read. However, sometimes it's not trivial to understand like when termwiz (i assume) doesn't know what's going on and just prints OSC Unspecified with a bunch stuff like this.

```
OSC Unspecified([[49, 51, 51, 55], [82, 101, 109, 111, 116, 101, 72, 111, 115, 116, 61, 102, 100, 110, 99, 114, 101, 100, 64, 77, 49, 88, 46, 108, 111, 99, 97, 108]])OSC ITermProprietary(CurrentDir("/Users/fdncred/src/escape-artist"))OSC Unspecified([[49, 51, 51, 55], [83, 104, 101, 108, 108, 73, 110, 116, 101, 103, 114, 97, 116, 105, 111, 110, 86, 101, 114, 115, 105, 111, 110, 61, 49, 55], [115, 104, 101, 108, 108, 61, 102, 105, 115, 104]])Welcome to fish, the friendly interactive shell
```
The hovers explain it though. it's the `\x1b[1337` codes. I'm surprised termwiz doesn't recognize them.

**Comment by rgwood** [comment]
Ah yeah,  that’s surprising that Termwiz doesn’t recognize those. Also I should probably display “unspecified” OSC sequences in a nicer way.

**Comment by fdncred** [comment]
Maybe just `OSC Unspecified` and the hover contains what it actually is instead of encoding as int arrays?

**Comment by rgwood** [comment]
Yeah I think that’s a good idea. I probably won’t have time until the weekend but feel free to submit a PR if you get bored, this would be a Rust-only change.

**Pull request merged**
